kind: Secret
cloudflare_email: ENC[AES256_GCM,data:WgxpFo/HRUZ0p6xhZYk8otHiofE=,iv:/2Xll0kUce3DkGXWEB8EjcPwWttRQrwNP0XNUppa8ls=,tag:7ewh2vL8QXor6yBZfHkHxQ==,type:str]
cloudflare_apikey: ENC[AES256_GCM,data:e9II8F5Fibi1jpxfkm7TlC558li2zPugJUnjdAZIAL+zRr+V6w==,iv:rDCb+FLebD/pHb10C/m6vRXKOROs8OK007y9kbBvGkU=,tag:dnSjgGjh+xo91TlqYUU3YQ==,type:str]
cloudflare_domain: ENC[AES256_GCM,data:MS4ja0DvBb2px2HOTZ+B,iv:gpImwY28ygbiJ3FEBNL4HFLXWlbDJImT9eYi+7jY5KU=,tag:ledrDk7tKaWMiYxeUAtsjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-14T12:54:10Z"
    mac: ENC[AES256_GCM,data:27N2XMZgFPRrD9Mx8nlxnzCzGIDf0DIBiPmPG2Jp3jEKj8CSuubH/1H3DAiIyYC6spSkziy98hN9yWkozHeqRm2jT+n9sB8j+wouHFA0H/ycDBiJyAv64kfnuJ9FUhnXi3IdR+FqqflI8L2+rDO/7qzd9WYFYdZiHmBgYDHlYrc=,iv:ffOvgL6fVeBgxDz42updwSnr7MjQ3bDN9Ib9mEcCnhs=,tag:MsYUktg/ulUH/ri0dAfAzA==,type:str]
    pgp:
        - created_at: "2022-03-15T12:07:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6ZIymqDCtVZARAANhlL5lkJdk70/UmCgKgwaJgjFH7/dGXC19vHV7z8opcH
            RhoTrjNNJgxAJbRjq3UN/3xz/n8L9funVIf9C4m4ela4TwbUQNoXxIAop+VqNamw
            offQ4vXgG8DWOeNBUhGEXe04xtjzyyYqgL41XflMH5mOFklZoH4jOVhU4HDJbBSL
            v7bO7oDEnsCiBTb5u2YkkDxCvj//MOrr9L+nE3EaDgmhchNn8gZ2XVvalBfW6XqE
            hE0OFCFAbFWquoU7MUPGhQHnFNYboZUwGhtpMsX1PoXcWwbN9K3VPlNP1VQFjBgV
            3sovUWtu80PxogukIKULnR4iMY6ckKWB2D3sk8uYX9TFtXb64PFA7dILh9hVnB4U
            YyjSJC1Y7xBnGDWFe1aNz9SQRLNfGTR1Vc5OMEdqedOgFh2wnp5F5JdwZuI/MkrH
            jBz0O+6SgdmXFHMrFOf3RfwlhBk95/V5IW5Hf77/CMjlHeG2MIA4yO85DdoRM0+r
            nYnUpI6evA67gbupSZjlZYnuLgLE2sDQRHrAHSMtai0DYnoEN3ogmAk5AVKKptRb
            1Jy/wRyCVdIuLJRdEo6xu5xL6jUayybFlK56bToebFU/Du3Fxy/njc9LgkataKF3
            aArpjIgn342CbUKlye4QZ3ufy8gp7i4JvzCICEhUTVB1yWtFukcfxEl1B0bP3CbS
            5gFIuRoSocwLpB2Z65PeU2xFwoA+vT7Jes4IbSLTSOfuZoj6iP3xRzUwMNFd9KBJ
            EtX+PBPs21zsYnnZehSTIdjkZ97EEUTNTgqxYcW7OJCdZuIQtpeOAA==
            =JFQY
            -----END PGP MESSAGE-----
          fp: 9BF3AFB540B69B4F7D5D05EFE31E4AB295E4270C
    unencrypted_regex: ^(kind)$
    version: 3.7.2
